[build]
    command = "yarn run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "8.9.4"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# Netlify subdomain
[[redirects]]
    from = "https://mxb.netlify.com/*"
    to = "https://mxb.at/:splat"
    status = 301

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
