[build]
    command = "yarn run build"
    publish = "dist"
    functions = "functions"

[build.environment]
    NODE_VERSION = "8.9.4"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# Netlify subdomain
[[redirects]]
    from = "https://mxb.netlify.com/*"
    to = "https://mxb.dev/:splat"
    status = 301
    force = true

# AT domain
[[redirects]]
    from = "https://mxb.at/*"
    to = "https://mxb.dev/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://www.mxb.at/*"
    to = "https://mxb.dev/:splat"
    status = 301
    force = true

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
